@echo off

echo HELLO WORLD
echo HELLO WORLD1
echo HELLO WORLD2
echo HELLO WORLD3
echo HELLO WORLD4
echo HELLO WORLD5
echo HELLO WORLD6

echo AAAAAAAAAAAAAAAA
echo HELLO WORLD1
echo HELLO WORLD2
echo sentence1 HELLO WORLD3
echo HELLO WORLD4
echo sentence1 HELLO WORLD5
echo HELLO WORLD6

echo sentence1 AAAAAAAAAAAAAAAA
echo HELLO WORLD1
echo sentence1 HELLO WORLD2
echo HELLO WORLD3
echo HELLO WORLD4
echo sentence1 HELLO WORLD5
echo HELLO WORLD6

timeout 2
echo sentence1 START
echo HELLO WORLD1
echo HELLO WORLD2
echo sentence1 HELLO WORLD3
echo HELLO WORLD4
echo HELLO WORLD5
echo sentence1 HELLO WORLD9

echo AAAAAAAAAAAAAAAA
echo HELLO WORLD1
echo HELLO WORLD2
echo sentence1 HELLO WORLD3
echo HELLO WORLD4
echo HELLO WORLD5
echo sentence1 HELLO WORLD7

echo sentence1 AAAAAAAAAAAAAAAA
echo HELLO WORLD1
echo HELLO WORLD2
echo sentence1 HELLO WORLD3
echo HELLO WORLD4
echo HELLO WORLD5
echo sentence1 HELLO WORLD8

echo sentence1 AAAAAAAAAAAAAAAA
echo HELLO WORLD1
echo HELLO WORLD2
echo sentence1 HELLO WORLD3
echo HELLO WORLD4
echo HELLO WORLD5
echo sentence1 HELLO WORLD9